services:
  app:
    build:
      context: .
      target: deps
    command: sh -c "npm install && npm run dev"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - NEXT_TELEMETRY_DISABLED=1
    # ホットリロードを有効にするために必要
    stdin_open: true
    tty: true
    # 依存関係が変わった場合に自動的に再起動する
    restart: unless-stopped

volumes:
  node_modules:
